package com.tss.tssmanager_backend.enums;

public enum SectorEmpresaEnum {
    // SECTOR PRIMARIO
    AGRICULTURA_CULTIVOS("11"),
    AGRICULTURA_GANADERIA("11"),
    AGRICULTURA_FORESTAL("11"),
    AGRICULTURA_PESCA("11"),

    // MINERÍA
    MINERIA_PETROLEO("21"),
    MINERIA_MINERALES("21"),
    MINERIA_NO_METALICOS("21"),
    MINERIA_CARBON("21"),

    // ENERGÍA Y SERVICIOS PÚBLICOS
    ENERGIA_ELECTRICA("22"),
    ENERGIA_GAS("22"),
    ENERGIA_AGUA("22"),
    ENERGIA_RENOVABLE("22"),

    // CONSTRUCCIÓN
    CONSTRUCCION_EDIFICACION("23"),
    CONSTRUCCION_INDUSTRIAL("23"),
    CONSTRUCCION_INFRAESTRUCTURA("23"),
    CONSTRUCCION_ESPECIALIZADA("23"),

    // MANUFACTURA
    MANUFACTURA_ALIMENTOS("31"),
    MANUFACTURA_TEXTIL("31"),
    MANUFACTURA_MADERA("31"),
    MANUFACTURA_PAPEL("31"),
    MANUFACTURA_QUIMICA("32"),
    MANUFACTURA_PLASTICOS("32"),
    MANUFACTURA_MINERALES("32"),
    MANUFACTURA_METAL_BASIC("33"),
    MANUFACTURA_METAL_PROD("33"),
    MANUFACTURA_MAQUINARIA("33"),
    MANUFACTURA_ELECTRONICA("33"),
    MANUFACTURA_ELECTRICA("33"),
    MANUFACTURA_TRANSPORTE("33"),
    MANUFACTURA_OTROS("33"),

    // COMERCIO AL POR MAYOR
    COMERCIO_MAYOR_AGRICOLA("43"),
    COMERCIO_MAYOR_ALIMENTOS("43"),
    COMERCIO_MAYOR_BEBIDAS("43"),
    COMERCIO_MAYOR_TEXTIL("43"),
    COMERCIO_MAYOR_FARMACEUTICO("43"),
    COMERCIO_MAYOR_QUIMICOS("43"),
    COMERCIO_MAYOR_PETROLEO("43"),
    COMERCIO_MAYOR_MATERIALES("43"),
    COMERCIO_MAYOR_MAQUINARIA("43"),
    COMERCIO_MAYOR_ELECTRONICA("43"),
    COMERCIO_MAYOR_VEHICULOS("43"),
    COMERCIO_MAYOR_MUEBLES("43"),
    COMERCIO_MAYOR_OTROS("43"),

    // COMERCIO AL POR MENOR
    COMERCIO_MENOR_ALIMENTOS("46"),
    COMERCIO_MENOR_ABARROTES("46"),
    COMERCIO_MENOR_FARMACIA("46"),
    COMERCIO_MENOR_COMBUSTIBLES("46"),
    COMERCIO_MENOR_VESTIDO("46"),
    COMERCIO_MENOR_MUEBLES("46"),
    COMERCIO_MENOR_ELECTRONICA("46"),
    COMERCIO_MENOR_FERRETERIA("46"),
    COMERCIO_MENOR_VEHICULOS("46"),
    COMERCIO_MENOR_REFACCIONES("46"),
    COMERCIO_MENOR_DEPARTAMENTAL("46"),
    COMERCIO_MENOR_OTROS("46"),

    // TRANSPORTE Y LOGÍSTICA
    TRANSPORTE_AEREO("48"),
    TRANSPORTE_FERROVIARIO("48"),
    TRANSPORTE_MARITIMO("48"),
    TRANSPORTE_TERRESTRE_CARGA("48"),
    TRANSPORTE_TERRESTRE_PASAJE("49"),
    TRANSPORTE_TURISTICO("49"),
    TRANSPORTE_CORREOS("49"),
    TRANSPORTE_ALMACENAMIENTO("49"),

    // MEDIOS E INFORMACIÓN
    MEDIOS_EDITORIALES("51"),
    MEDIOS_AUDIOVISUAL("51"),
    MEDIOS_RADIO_TV("51"),
    MEDIOS_TELECOMUNICACIONES("51"),
    MEDIOS_PROCESAMIENTO_DATOS("51"),
    MEDIOS_OTROS("51"),

    // SERVICIOS FINANCIEROS
    FINANCIERO_BANCA("52"),
    FINANCIERO_VALORES("52"),
    FINANCIERO_SEGUROS("52"),
    FINANCIERO_PENSIONES("52"),
    FINANCIERO_OTROS("52"),

    // INMOBILIARIO Y ALQUILER
    INMOBILIARIO_COMPRAVENTA("53"),
    INMOBILIARIO_ALQUILER("53"),
    INMOBILIARIO_MAQUINARIA("53"),
    INMOBILIARIO_VEHICULOS("53"),
    INMOBILIARIO_OTROS("53"),

    // SERVICIOS PROFESIONALES
    PROFESIONAL_JURIDICOS("54"),
    PROFESIONAL_CONTABLES("54"),
    PROFESIONAL_ARQUITECTURA("54"),
    PROFESIONAL_DISENO("54"),
    PROFESIONAL_CONSULTORIA("54"),
    PROFESIONAL_INVESTIGACION("54"),
    PROFESIONAL_PUBLICIDAD("54"),
    PROFESIONAL_VETERINARIOS("54"),
    PROFESIONAL_OTROS("54"),

    // CORPORATIVOS
    CORPORATIVO_HOLDING("55"),
    CORPORATIVO_MATRIZ("55"),

    // APOYO A NEGOCIOS
    APOYO_EMPLEO("56"),
    APOYO_ADMINISTRATIVO("56"),
    APOYO_SEGURIDAD("56"),
    APOYO_LIMPIEZA("56"),
    APOYO_PAISAJISMO("56"),
    APOYO_VIAJES("56"),
    APOYO_INVESTIGACION("56"),
    APOYO_DESECHOS("56"),
    APOYO_OTROS("56"),

    // EDUCACIÓN
    EDUCACION_PREESCOLAR("61"),
    EDUCACION_PRIMARIA("61"),
    EDUCACION_SECUNDARIA("61"),
    EDUCACION_MEDIA_SUPERIOR("61"),
    EDUCACION_SUPERIOR("61"),
    EDUCACION_POSGRADO("61"),
    EDUCACION_TECNICA("61"),
    EDUCACION_OTROS("61"),

    // SALUD
    SALUD_HOSPITALES("62"),
    SALUD_AMBULATORIOS("62"),
    SALUD_ASISTENCIA_SOCIAL("62"),

    // ESPARCIMIENTO
    ESPARCIMIENTO_ARTISTICOS("71"),
    ESPARCIMIENTO_DEPORTIVOS("71"),
    ESPARCIMIENTO_RECREATIVOS("71"),
    ESPARCIMIENTO_MUSEOS("71"),
    ESPARCIMIENTO_OTROS("71"),

    // ALOJAMIENTO Y ALIMENTOS
    ALOJAMIENTO_HOTELES("72"),
    ALOJAMIENTO_TEMPORAL("72"),
    ALIMENTOS_RESTAURANTES("72"),
    ALIMENTOS_LIMITADO("72"),
    ALIMENTOS_PREPARACION("72"),

    // OTROS SERVICIOS
    OTROS_REPARACION("81"),
    OTROS_PERSONALES("81"),
    OTROS_RELIGIOSOS("81"),
    OTROS_CIVICAS("81"),
    OTROS_PROFESIONALES("81"),
    OTROS_LABORALES("81"),
    OTROS_POLITICAS("81"),

    // GUBERNAMENTAL
    GUBERNAMENTAL_FEDERAL("93"),
    GUBERNAMENTAL_ESTATAL("93"),
    GUBERNAMENTAL_MUNICIPAL("93"),
    GUBERNAMENTAL_JUSTICIA("93"),
    GUBERNAMENTAL_SEGURIDAD("93"),
    GUBERNAMENTAL_OTROS("93"),

    PARTICULAR("99"),
    ;

    private final String codigo;

    SectorEmpresaEnum(String codigo) {
        this.codigo = codigo;
    }

    public String getCodigo() {
        return codigo;
    }
}