package com.tss.tssmanager_backend.enums;

public enum SiguienteAccionEnum {
    REGRESAR_LLAMADA,
    MANDAR_MENSAJE,
    MANDAR_INFORMACION,
    _1ER_SEGUIMIENTO,
    _2DO_SEGUIMIENTO,
    _3ER_SEGUIMIENTO,
    REUNION,
    MANDAR_COTIZACION,
    POSIBLE_PERDIDO,
    PERDIDO,
    BUSCAR_OTRO_CONTACTO,
    REALIZAR_DEMO,
    VENTA,
    COBRANZA,
    INSTALACION,
    REVISION_TECNICA,
    VISITAR_EN_FISICO,
    CONTACTAR_DESPUES
}